/* eslint-disable max-lines -- generated snapshot of the public iptv-org catalogue */
// GENERATED FILE — do not edit by hand.
// Regenerate with: node tools/channel-sources/build-catalog.mjs
// Snapshot taken: 2026-08-29
import type { GeneratedChannelSource } from './channel-source.model';

export const GENERATED_CHANNEL_SOURCES: readonly GeneratedChannelSource[] = [
    {
        id: 'iptv-org:country:us',
        kind: 'country',
        code: 'us',
        name: 'United States',
        flag: '🇺🇸',
        url: 'https://iptv-org.github.io/iptv/countries/us.m3u',
        streamCount: 2894,
    },
    {
        id: 'iptv-org:country:in',
        kind: 'country',
        code: 'in',
        name: 'India',
        flag: '🇮🇳',
        url: 'https://iptv-org.github.io/iptv/countries/in.m3u',
        streamCount: 1215,
    },
    {
        id: 'iptv-org:country:ru',
        kind: 'country',
        code: 'ru',
        name: 'Russia',
        flag: '🇷🇺',
        url: 'https://iptv-org.github.io/iptv/countries/ru.m3u',
        streamCount: 1000,
    },
    {
        id: 'iptv-org:country:de',
        kind: 'country',
        code: 'de',
        name: 'Germany',
        flag: '🇩🇪',
        url: 'https://iptv-org.github.io/iptv/countries/de.m3u',
        streamCount: 568,
    },
    {
        id: 'iptv-org:country:br',
        kind: 'country',
        code: 'br',
        name: 'Brazil',
        flag: '🇧🇷',
        url: 'https://iptv-org.github.io/iptv/countries/br.m3u',
        streamCount: 537,
    },
    {
        id: 'iptv-org:country:uk',
        kind: 'country',
        code: 'uk',
        name: 'United Kingdom',
        flag: '🇬🇧',
        url: 'https://iptv-org.github.io/iptv/countries/uk.m3u',
        streamCount: 511,
    },
    {
        id: 'iptv-org:country:se',
        kind: 'country',
        code: 'se',
        name: 'Sweden',
        flag: '🇸🇪',
        url: 'https://iptv-org.github.io/iptv/countries/se.m3u',
        streamCount: 389,
    },
    {
        id: 'iptv-org:country:es',
        kind: 'country',
        code: 'es',
        name: 'Spain',
        flag: '🇪🇸',
        url: 'https://iptv-org.github.io/iptv/countries/es.m3u',
        streamCount: 327,
    },
    {
        id: 'iptv-org:country:fr',
        kind: 'country',
        code: 'fr',
        name: 'France',
        flag: '🇫🇷',
        url: 'https://iptv-org.github.io/iptv/countries/fr.m3u',
        streamCount: 326,
    },
    {
        id: 'iptv-org:country:cn',
        kind: 'country',
        code: 'cn',
        name: 'China',
        flag: '🇨🇳',
        url: 'https://iptv-org.github.io/iptv/countries/cn.m3u',
        streamCount: 313,
    },
    {
        id: 'iptv-org:country:it',
        kind: 'country',
        code: 'it',
        name: 'Italy',
        flag: '🇮🇹',
        url: 'https://iptv-org.github.io/iptv/countries/it.m3u',
        streamCount: 304,
    },
    {
        id: 'iptv-org:country:cl',
        kind: 'country',
        code: 'cl',
        name: 'Chile',
        flag: '🇨🇱',
        url: 'https://iptv-org.github.io/iptv/countries/cl.m3u',
        streamCount: 293,
    },
    {
        id: 'iptv-org:country:do',
        kind: 'country',
        code: 'do',
        name: 'Dominican Republic',
        flag: '🇩🇴',
        url: 'https://iptv-org.github.io/iptv/countries/do.m3u',
        streamCount: 259,
    },
    {
        id: 'iptv-org:country:pe',
        kind: 'country',
        code: 'pe',
        name: 'Peru',
        flag: '🇵🇪',
        url: 'https://iptv-org.github.io/iptv/countries/pe.m3u',
        streamCount: 251,
    },
    {
        id: 'iptv-org:country:tr',
        kind: 'country',
        code: 'tr',
        name: 'Turkiye',
        flag: '🇹🇷',
        url: 'https://iptv-org.github.io/iptv/countries/tr.m3u',
        streamCount: 236,
    },
    {
        id: 'iptv-org:country:ca',
        kind: 'country',
        code: 'ca',
        name: 'Canada',
        flag: '🇨🇦',
        url: 'https://iptv-org.github.io/iptv/countries/ca.m3u',
        streamCount: 220,
    },
    {
        id: 'iptv-org:country:nl',
        kind: 'country',
        code: 'nl',
        name: 'Netherlands',
        flag: '🇳🇱',
        url: 'https://iptv-org.github.io/iptv/countries/nl.m3u',
        streamCount: 216,
    },
    {
        id: 'iptv-org:country:ar',
        kind: 'country',
        code: 'ar',
        name: 'Argentina',
        flag: '🇦🇷',
        url: 'https://iptv-org.github.io/iptv/countries/ar.m3u',
        streamCount: 209,
    },
    {
        id: 'iptv-org:country:id',
        kind: 'country',
        code: 'id',
        name: 'Indonesia',
        flag: '🇮🇩',
        url: 'https://iptv-org.github.io/iptv/countries/id.m3u',
        streamCount: 198,
    },
    {
        id: 'iptv-org:country:mx',
        kind: 'country',
        code: 'mx',
        name: 'Mexico',
        flag: '🇲🇽',
        url: 'https://iptv-org.github.io/iptv/countries/mx.m3u',
        streamCount: 184,
    },
    {
        id: 'iptv-org:country:ua',
        kind: 'country',
        code: 'ua',
        name: 'Ukraine',
        flag: '🇺🇦',
        url: 'https://iptv-org.github.io/iptv/countries/ua.m3u',
        streamCount: 169,
    },
    {
        id: 'iptv-org:country:pl',
        kind: 'country',
        code: 'pl',
        name: 'Poland',
        flag: '🇵🇱',
        url: 'https://iptv-org.github.io/iptv/countries/pl.m3u',
        streamCount: 154,
    },
    {
        id: 'iptv-org:country:hu',
        kind: 'country',
        code: 'hu',
        name: 'Hungary',
        flag: '🇭🇺',
        url: 'https://iptv-org.github.io/iptv/countries/hu.m3u',
        streamCount: 149,
    },
    {
        id: 'iptv-org:country:vn',
        kind: 'country',
        code: 'vn',
        name: 'Vietnam',
        flag: '🇻🇳',
        url: 'https://iptv-org.github.io/iptv/countries/vn.m3u',
        streamCount: 148,
    },
    {
        id: 'iptv-org:country:co',
        kind: 'country',
        code: 'co',
        name: 'Colombia',
        flag: '🇨🇴',
        url: 'https://iptv-org.github.io/iptv/countries/co.m3u',
        streamCount: 135,
    },
    {
        id: 'iptv-org:country:ir',
        kind: 'country',
        code: 'ir',
        name: 'Iran',
        flag: '🇮🇷',
        url: 'https://iptv-org.github.io/iptv/countries/ir.m3u',
        streamCount: 126,
    },
    {
        id: 'iptv-org:country:pk',
        kind: 'country',
        code: 'pk',
        name: 'Pakistan',
        flag: '🇵🇰',
        url: 'https://iptv-org.github.io/iptv/countries/pk.m3u',
        streamCount: 110,
    },
    {
        id: 'iptv-org:country:ec',
        kind: 'country',
        code: 'ec',
        name: 'Ecuador',
        flag: '🇪🇨',
        url: 'https://iptv-org.github.io/iptv/countries/ec.m3u',
        streamCount: 104,
    },
    {
        id: 'iptv-org:country:ro',
        kind: 'country',
        code: 'ro',
        name: 'Romania',
        flag: '🇷🇴',
        url: 'https://iptv-org.github.io/iptv/countries/ro.m3u',
        streamCount: 104,
    },
    {
        id: 'iptv-org:country:bo',
        kind: 'country',
        code: 'bo',
        name: 'Bolivia',
        flag: '🇧🇴',
        url: 'https://iptv-org.github.io/iptv/countries/bo.m3u',
        streamCount: 95,
    },
    {
        id: 'iptv-org:country:kr',
        kind: 'country',
        code: 'kr',
        name: 'South Korea',
        flag: '🇰🇷',
        url: 'https://iptv-org.github.io/iptv/countries/kr.m3u',
        streamCount: 92,
    },
    {
        id: 'iptv-org:country:th',
        kind: 'country',
        code: 'th',
        name: 'Thailand',
        flag: '🇹🇭',
        url: 'https://iptv-org.github.io/iptv/countries/th.m3u',
        streamCount: 91,
    },
    {
        id: 'iptv-org:country:cr',
        kind: 'country',
        code: 'cr',
        name: 'Costa Rica',
        flag: '🇨🇷',
        url: 'https://iptv-org.github.io/iptv/countries/cr.m3u',
        streamCount: 86,
    },
    {
        id: 'iptv-org:country:hn',
        kind: 'country',
        code: 'hn',
        name: 'Honduras',
        flag: '🇭🇳',
        url: 'https://iptv-org.github.io/iptv/countries/hn.m3u',
        streamCount: 85,
    },
    {
        id: 'iptv-org:country:ve',
        kind: 'country',
        code: 've',
        name: 'Venezuela',
        flag: '🇻🇪',
        url: 'https://iptv-org.github.io/iptv/countries/ve.m3u',
        streamCount: 80,
    },
    {
        id: 'iptv-org:country:cz',
        kind: 'country',
        code: 'cz',
        name: 'Czech Republic',
        flag: '🇨🇿',
        url: 'https://iptv-org.github.io/iptv/countries/cz.m3u',
        streamCount: 79,
    },
    {
        id: 'iptv-org:country:mn',
        kind: 'country',
        code: 'mn',
        name: 'Mongolia',
        flag: '🇲🇳',
        url: 'https://iptv-org.github.io/iptv/countries/mn.m3u',
        streamCount: 79,
    },
    {
        id: 'iptv-org:country:gr',
        kind: 'country',
        code: 'gr',
        name: 'Greece',
        flag: '🇬🇷',
        url: 'https://iptv-org.github.io/iptv/countries/gr.m3u',
        streamCount: 78,
    },
    {
        id: 'iptv-org:country:sa',
        kind: 'country',
        code: 'sa',
        name: 'Saudi Arabia',
        flag: '🇸🇦',
        url: 'https://iptv-org.github.io/iptv/countries/sa.m3u',
        streamCount: 72,
    },
    {
        id: 'iptv-org:country:py',
        kind: 'country',
        code: 'py',
        name: 'Paraguay',
        flag: '🇵🇾',
        url: 'https://iptv-org.github.io/iptv/countries/py.m3u',
        streamCount: 71,
    },
    {
        id: 'iptv-org:country:bg',
        kind: 'country',
        code: 'bg',
        name: 'Bulgaria',
        flag: '🇧🇬',
        url: 'https://iptv-org.github.io/iptv/countries/bg.m3u',
        streamCount: 70,
    },
    {
        id: 'iptv-org:country:rs',
        kind: 'country',
        code: 'rs',
        name: 'Serbia',
        flag: '🇷🇸',
        url: 'https://iptv-org.github.io/iptv/countries/rs.m3u',
        streamCount: 70,
    },
    {
        id: 'iptv-org:country:gt',
        kind: 'country',
        code: 'gt',
        name: 'Guatemala',
        flag: '🇬🇹',
        url: 'https://iptv-org.github.io/iptv/countries/gt.m3u',
        streamCount: 68,
    },
    {
        id: 'iptv-org:country:iq',
        kind: 'country',
        code: 'iq',
        name: 'Iraq',
        flag: '🇮🇶',
        url: 'https://iptv-org.github.io/iptv/countries/iq.m3u',
        streamCount: 67,
    },
    {
        id: 'iptv-org:country:pt',
        kind: 'country',
        code: 'pt',
        name: 'Portugal',
        flag: '🇵🇹',
        url: 'https://iptv-org.github.io/iptv/countries/pt.m3u',
        streamCount: 66,
    },
    {
        id: 'iptv-org:country:be',
        kind: 'country',
        code: 'be',
        name: 'Belgium',
        flag: '🇧🇪',
        url: 'https://iptv-org.github.io/iptv/countries/be.m3u',
        streamCount: 62,
    },
    {
        id: 'iptv-org:country:qa',
        kind: 'country',
        code: 'qa',
        name: 'Qatar',
        flag: '🇶🇦',
        url: 'https://iptv-org.github.io/iptv/countries/qa.m3u',
        streamCount: 62,
    },
    {
        id: 'iptv-org:country:sk',
        kind: 'country',
        code: 'sk',
        name: 'Slovakia',
        flag: '🇸🇰',
        url: 'https://iptv-org.github.io/iptv/countries/sk.m3u',
        streamCount: 60,
    },
    {
        id: 'iptv-org:country:ng',
        kind: 'country',
        code: 'ng',
        name: 'Nigeria',
        flag: '🇳🇬',
        url: 'https://iptv-org.github.io/iptv/countries/ng.m3u',
        streamCount: 59,
    },
    {
        id: 'iptv-org:country:au',
        kind: 'country',
        code: 'au',
        name: 'Australia',
        flag: '🇦🇺',
        url: 'https://iptv-org.github.io/iptv/countries/au.m3u',
        streamCount: 56,
    },
    {
        id: 'iptv-org:country:at',
        kind: 'country',
        code: 'at',
        name: 'Austria',
        flag: '🇦🇹',
        url: 'https://iptv-org.github.io/iptv/countries/at.m3u',
        streamCount: 54,
    },
    {
        id: 'iptv-org:country:ae',
        kind: 'country',
        code: 'ae',
        name: 'United Arab Emirates',
        flag: '🇦🇪',
        url: 'https://iptv-org.github.io/iptv/countries/ae.m3u',
        streamCount: 47,
    },
    {
        id: 'iptv-org:country:kz',
        kind: 'country',
        code: 'kz',
        name: 'Kazakhstan',
        flag: '🇰🇿',
        url: 'https://iptv-org.github.io/iptv/countries/kz.m3u',
        streamCount: 44,
    },
    {
        id: 'iptv-org:country:ke',
        kind: 'country',
        code: 'ke',
        name: 'Kenya',
        flag: '🇰🇪',
        url: 'https://iptv-org.github.io/iptv/countries/ke.m3u',
        streamCount: 39,
    },
    {
        id: 'iptv-org:country:ch',
        kind: 'country',
        code: 'ch',
        name: 'Switzerland',
        flag: '🇨🇭',
        url: 'https://iptv-org.github.io/iptv/countries/ch.m3u',
        streamCount: 37,
    },
    {
        id: 'iptv-org:country:uz',
        kind: 'country',
        code: 'uz',
        name: 'Uzbekistan',
        flag: '🇺🇿',
        url: 'https://iptv-org.github.io/iptv/countries/uz.m3u',
        streamCount: 37,
    },
    {
        id: 'iptv-org:country:kh',
        kind: 'country',
        code: 'kh',
        name: 'Cambodia',
        flag: '🇰🇭',
        url: 'https://iptv-org.github.io/iptv/countries/kh.m3u',
        streamCount: 36,
    },
    {
        id: 'iptv-org:country:hr',
        kind: 'country',
        code: 'hr',
        name: 'Croatia',
        flag: '🇭🇷',
        url: 'https://iptv-org.github.io/iptv/countries/hr.m3u',
        streamCount: 36,
    },
    {
        id: 'iptv-org:country:sv',
        kind: 'country',
        code: 'sv',
        name: 'El Salvador',
        flag: '🇸🇻',
        url: 'https://iptv-org.github.io/iptv/countries/sv.m3u',
        streamCount: 36,
    },
    {
        id: 'iptv-org:country:lb',
        kind: 'country',
        code: 'lb',
        name: 'Lebanon',
        flag: '🇱🇧',
        url: 'https://iptv-org.github.io/iptv/countries/lb.m3u',
        streamCount: 35,
    },
    {
        id: 'iptv-org:country:al',
        kind: 'country',
        code: 'al',
        name: 'Albania',
        flag: '🇦🇱',
        url: 'https://iptv-org.github.io/iptv/countries/al.m3u',
        streamCount: 33,
    },
    {
        id: 'iptv-org:country:fi',
        kind: 'country',
        code: 'fi',
        name: 'Finland',
        flag: '🇫🇮',
        url: 'https://iptv-org.github.io/iptv/countries/fi.m3u',
        streamCount: 33,
    },
    {
        id: 'iptv-org:country:bd',
        kind: 'country',
        code: 'bd',
        name: 'Bangladesh',
        flag: '🇧🇩',
        url: 'https://iptv-org.github.io/iptv/countries/bd.m3u',
        streamCount: 32,
    },
    {
        id: 'iptv-org:country:il',
        kind: 'country',
        code: 'il',
        name: 'Israel',
        flag: '🇮🇱',
        url: 'https://iptv-org.github.io/iptv/countries/il.m3u',
        streamCount: 32,
    },
    {
        id: 'iptv-org:country:by',
        kind: 'country',
        code: 'by',
        name: 'Belarus',
        flag: '🇧🇾',
        url: 'https://iptv-org.github.io/iptv/countries/by.m3u',
        streamCount: 30,
    },
    {
        id: 'iptv-org:country:md',
        kind: 'country',
        code: 'md',
        name: 'Moldova',
        flag: '🇲🇩',
        url: 'https://iptv-org.github.io/iptv/countries/md.m3u',
        streamCount: 30,
    },
    {
        id: 'iptv-org:country:mk',
        kind: 'country',
        code: 'mk',
        name: 'North Macedonia',
        flag: '🇲🇰',
        url: 'https://iptv-org.github.io/iptv/countries/mk.m3u',
        streamCount: 30,
    },
    {
        id: 'iptv-org:country:za',
        kind: 'country',
        code: 'za',
        name: 'South Africa',
        flag: '🇿🇦',
        url: 'https://iptv-org.github.io/iptv/countries/za.m3u',
        streamCount: 29,
    },
    {
        id: 'iptv-org:country:ba',
        kind: 'country',
        code: 'ba',
        name: 'Bosnia and Herzegovina',
        flag: '🇧🇦',
        url: 'https://iptv-org.github.io/iptv/countries/ba.m3u',
        streamCount: 28,
    },
    {
        id: 'iptv-org:country:tw',
        kind: 'country',
        code: 'tw',
        name: 'Taiwan',
        flag: '🇹🇼',
        url: 'https://iptv-org.github.io/iptv/countries/tw.m3u',
        streamCount: 28,
    },
    {
        id: 'iptv-org:country:pr',
        kind: 'country',
        code: 'pr',
        name: 'Puerto Rico',
        flag: '🇵🇷',
        url: 'https://iptv-org.github.io/iptv/countries/pr.m3u',
        streamCount: 27,
    },
    {
        id: 'iptv-org:country:hk',
        kind: 'country',
        code: 'hk',
        name: 'Hong Kong',
        flag: '🇭🇰',
        url: 'https://iptv-org.github.io/iptv/countries/hk.m3u',
        streamCount: 26,
    },
    {
        id: 'iptv-org:country:sg',
        kind: 'country',
        code: 'sg',
        name: 'Singapore',
        flag: '🇸🇬',
        url: 'https://iptv-org.github.io/iptv/countries/sg.m3u',
        streamCount: 26,
    },
    {
        id: 'iptv-org:country:ee',
        kind: 'country',
        code: 'ee',
        name: 'Estonia',
        flag: '🇪🇪',
        url: 'https://iptv-org.github.io/iptv/countries/ee.m3u',
        streamCount: 25,
    },
    {
        id: 'iptv-org:country:ge',
        kind: 'country',
        code: 'ge',
        name: 'Georgia',
        flag: '🇬🇪',
        url: 'https://iptv-org.github.io/iptv/countries/ge.m3u',
        streamCount: 25,
    },
    {
        id: 'iptv-org:country:si',
        kind: 'country',
        code: 'si',
        name: 'Slovenia',
        flag: '🇸🇮',
        url: 'https://iptv-org.github.io/iptv/countries/si.m3u',
        streamCount: 24,
    },
    {
        id: 'iptv-org:country:ps',
        kind: 'country',
        code: 'ps',
        name: 'Palestine',
        flag: '🇵🇸',
        url: 'https://iptv-org.github.io/iptv/countries/ps.m3u',
        streamCount: 23,
    },
    {
        id: 'iptv-org:country:pa',
        kind: 'country',
        code: 'pa',
        name: 'Panama',
        flag: '🇵🇦',
        url: 'https://iptv-org.github.io/iptv/countries/pa.m3u',
        streamCount: 23,
    },
    {
        id: 'iptv-org:country:ug',
        kind: 'country',
        code: 'ug',
        name: 'Uganda',
        flag: '🇺🇬',
        url: 'https://iptv-org.github.io/iptv/countries/ug.m3u',
        streamCount: 23,
    },
    {
        id: 'iptv-org:country:ie',
        kind: 'country',
        code: 'ie',
        name: 'Ireland',
        flag: '🇮🇪',
        url: 'https://iptv-org.github.io/iptv/countries/ie.m3u',
        streamCount: 22,
    },
    {
        id: 'iptv-org:country:my',
        kind: 'country',
        code: 'my',
        name: 'Malaysia',
        flag: '🇲🇾',
        url: 'https://iptv-org.github.io/iptv/countries/my.m3u',
        streamCount: 22,
    },
    {
        id: 'iptv-org:country:ni',
        kind: 'country',
        code: 'ni',
        name: 'Nicaragua',
        flag: '🇳🇮',
        url: 'https://iptv-org.github.io/iptv/countries/ni.m3u',
        streamCount: 22,
    },
    {
        id: 'iptv-org:country:jp',
        kind: 'country',
        code: 'jp',
        name: 'Japan',
        flag: '🇯🇵',
        url: 'https://iptv-org.github.io/iptv/countries/jp.m3u',
        streamCount: 21,
    },
    {
        id: 'iptv-org:country:az',
        kind: 'country',
        code: 'az',
        name: 'Azerbaijan',
        flag: '🇦🇿',
        url: 'https://iptv-org.github.io/iptv/countries/az.m3u',
        streamCount: 20,
    },
    {
        id: 'iptv-org:country:ci',
        kind: 'country',
        code: 'ci',
        name: 'Ivory Coast',
        flag: '🇨🇮',
        url: 'https://iptv-org.github.io/iptv/countries/ci.m3u',
        streamCount: 20,
    },
    {
        id: 'iptv-org:country:jo',
        kind: 'country',
        code: 'jo',
        name: 'Jordan',
        flag: '🇯🇴',
        url: 'https://iptv-org.github.io/iptv/countries/jo.m3u',
        streamCount: 20,
    },
    {
        id: 'iptv-org:country:mm',
        kind: 'country',
        code: 'mm',
        name: 'Myanmar',
        flag: '🇲🇲',
        url: 'https://iptv-org.github.io/iptv/countries/mm.m3u',
        streamCount: 19,
    },
    {
        id: 'iptv-org:country:no',
        kind: 'country',
        code: 'no',
        name: 'Norway',
        flag: '🇳🇴',
        url: 'https://iptv-org.github.io/iptv/countries/no.m3u',
        streamCount: 19,
    },
    {
        id: 'iptv-org:country:cy',
        kind: 'country',
        code: 'cy',
        name: 'Cyprus',
        flag: '🇨🇾',
        url: 'https://iptv-org.github.io/iptv/countries/cy.m3u',
        streamCount: 18,
    },
    {
        id: 'iptv-org:country:eg',
        kind: 'country',
        code: 'eg',
        name: 'Egypt',
        flag: '🇪🇬',
        url: 'https://iptv-org.github.io/iptv/countries/eg.m3u',
        streamCount: 18,
    },
    {
        id: 'iptv-org:country:lt',
        kind: 'country',
        code: 'lt',
        name: 'Lithuania',
        flag: '🇱🇹',
        url: 'https://iptv-org.github.io/iptv/countries/lt.m3u',
        streamCount: 18,
    },
    {
        id: 'iptv-org:country:bz',
        kind: 'country',
        code: 'bz',
        name: 'Belize',
        flag: '🇧🇿',
        url: 'https://iptv-org.github.io/iptv/countries/bz.m3u',
        streamCount: 17,
    },
    {
        id: 'iptv-org:country:cm',
        kind: 'country',
        code: 'cm',
        name: 'Cameroon',
        flag: '🇨🇲',
        url: 'https://iptv-org.github.io/iptv/countries/cm.m3u',
        streamCount: 17,
    },
    {
        id: 'iptv-org:country:cd',
        kind: 'country',
        code: 'cd',
        name: 'Democratic Republic of the Congo',
        flag: '🇨🇩',
        url: 'https://iptv-org.github.io/iptv/countries/cd.m3u',
        streamCount: 16,
    },
    {
        id: 'iptv-org:country:xk',
        kind: 'country',
        code: 'xk',
        name: 'Kosovo',
        flag: '🇽🇰',
        url: 'https://iptv-org.github.io/iptv/countries/xk.m3u',
        streamCount: 16,
    },
    {
        id: 'iptv-org:country:nz',
        kind: 'country',
        code: 'nz',
        name: 'New Zealand',
        flag: '🇳🇿',
        url: 'https://iptv-org.github.io/iptv/countries/nz.m3u',
        streamCount: 16,
    },
    {
        id: 'iptv-org:country:sy',
        kind: 'country',
        code: 'sy',
        name: 'Syria',
        flag: '🇸🇾',
        url: 'https://iptv-org.github.io/iptv/countries/sy.m3u',
        streamCount: 16,
    },
    {
        id: 'iptv-org:country:tm',
        kind: 'country',
        code: 'tm',
        name: 'Turkmenistan',
        flag: '🇹🇲',
        url: 'https://iptv-org.github.io/iptv/countries/tm.m3u',
        streamCount: 16,
    },
    {
        id: 'iptv-org:country:aw',
        kind: 'country',
        code: 'aw',
        name: 'Aruba',
        flag: '🇦🇼',
        url: 'https://iptv-org.github.io/iptv/countries/aw.m3u',
        streamCount: 15,
    },
    {
        id: 'iptv-org:country:lv',
        kind: 'country',
        code: 'lv',
        name: 'Latvia',
        flag: '🇱🇻',
        url: 'https://iptv-org.github.io/iptv/countries/lv.m3u',
        streamCount: 15,
    },
    {
        id: 'iptv-org:country:sn',
        kind: 'country',
        code: 'sn',
        name: 'Senegal',
        flag: '🇸🇳',
        url: 'https://iptv-org.github.io/iptv/countries/sn.m3u',
        streamCount: 15,
    },
    {
        id: 'iptv-org:country:lk',
        kind: 'country',
        code: 'lk',
        name: 'Sri Lanka',
        flag: '🇱🇰',
        url: 'https://iptv-org.github.io/iptv/countries/lk.m3u',
        streamCount: 15,
    },
    {
        id: 'iptv-org:country:af',
        kind: 'country',
        code: 'af',
        name: 'Afghanistan',
        flag: '🇦🇫',
        url: 'https://iptv-org.github.io/iptv/countries/af.m3u',
        streamCount: 14,
    },
    {
        id: 'iptv-org:country:dk',
        kind: 'country',
        code: 'dk',
        name: 'Denmark',
        flag: '🇩🇰',
        url: 'https://iptv-org.github.io/iptv/countries/dk.m3u',
        streamCount: 14,
    },
    {
        id: 'iptv-org:country:ht',
        kind: 'country',
        code: 'ht',
        name: 'Haiti',
        flag: '🇭🇹',
        url: 'https://iptv-org.github.io/iptv/countries/ht.m3u',
        streamCount: 14,
    },
    {
        id: 'iptv-org:country:kw',
        kind: 'country',
        code: 'kw',
        name: 'Kuwait',
        flag: '🇰🇼',
        url: 'https://iptv-org.github.io/iptv/countries/kw.m3u',
        streamCount: 14,
    },
    {
        id: 'iptv-org:country:kg',
        kind: 'country',
        code: 'kg',
        name: 'Kyrgyzstan',
        flag: '🇰🇬',
        url: 'https://iptv-org.github.io/iptv/countries/kg.m3u',
        streamCount: 14,
    },
    {
        id: 'iptv-org:country:ma',
        kind: 'country',
        code: 'ma',
        name: 'Morocco',
        flag: '🇲🇦',
        url: 'https://iptv-org.github.io/iptv/countries/ma.m3u',
        streamCount: 14,
    },
    {
        id: 'iptv-org:country:np',
        kind: 'country',
        code: 'np',
        name: 'Nepal',
        flag: '🇳🇵',
        url: 'https://iptv-org.github.io/iptv/countries/np.m3u',
        streamCount: 14,
    },
    {
        id: 'iptv-org:country:ph',
        kind: 'country',
        code: 'ph',
        name: 'Philippines',
        flag: '🇵🇭',
        url: 'https://iptv-org.github.io/iptv/countries/ph.m3u',
        streamCount: 14,
    },
    {
        id: 'iptv-org:country:tj',
        kind: 'country',
        code: 'tj',
        name: 'Tajikistan',
        flag: '🇹🇯',
        url: 'https://iptv-org.github.io/iptv/countries/tj.m3u',
        streamCount: 14,
    },
    {
        id: 'iptv-org:country:am',
        kind: 'country',
        code: 'am',
        name: 'Armenia',
        flag: '🇦🇲',
        url: 'https://iptv-org.github.io/iptv/countries/am.m3u',
        streamCount: 12,
    },
    {
        id: 'iptv-org:country:gh',
        kind: 'country',
        code: 'gh',
        name: 'Ghana',
        flag: '🇬🇭',
        url: 'https://iptv-org.github.io/iptv/countries/gh.m3u',
        streamCount: 12,
    },
    {
        id: 'iptv-org:country:lu',
        kind: 'country',
        code: 'lu',
        name: 'Luxembourg',
        flag: '🇱🇺',
        url: 'https://iptv-org.github.io/iptv/countries/lu.m3u',
        streamCount: 12,
    },
    {
        id: 'iptv-org:country:mt',
        kind: 'country',
        code: 'mt',
        name: 'Malta',
        flag: '🇲🇹',
        url: 'https://iptv-org.github.io/iptv/countries/mt.m3u',
        streamCount: 12,
    },
    {
        id: 'iptv-org:country:tg',
        kind: 'country',
        code: 'tg',
        name: 'Togo',
        flag: '🇹🇬',
        url: 'https://iptv-org.github.io/iptv/countries/tg.m3u',
        streamCount: 11,
    },
    {
        id: 'iptv-org:country:bj',
        kind: 'country',
        code: 'bj',
        name: 'Benin',
        flag: '🇧🇯',
        url: 'https://iptv-org.github.io/iptv/countries/bj.m3u',
        streamCount: 10,
    },
    {
        id: 'iptv-org:country:la',
        kind: 'country',
        code: 'la',
        name: 'Laos',
        flag: '🇱🇦',
        url: 'https://iptv-org.github.io/iptv/countries/la.m3u',
        streamCount: 9,
    },
    {
        id: 'iptv-org:country:mo',
        kind: 'country',
        code: 'mo',
        name: 'Macao',
        flag: '🇲🇴',
        url: 'https://iptv-org.github.io/iptv/countries/mo.m3u',
        streamCount: 9,
    },
    {
        id: 'iptv-org:country:mv',
        kind: 'country',
        code: 'mv',
        name: 'Maldives',
        flag: '🇲🇻',
        url: 'https://iptv-org.github.io/iptv/countries/mv.m3u',
        streamCount: 9,
    },
    {
        id: 'iptv-org:country:mz',
        kind: 'country',
        code: 'mz',
        name: 'Mozambique',
        flag: '🇲🇿',
        url: 'https://iptv-org.github.io/iptv/countries/mz.m3u',
        streamCount: 9,
    },
    {
        id: 'iptv-org:country:rw',
        kind: 'country',
        code: 'rw',
        name: 'Rwanda',
        flag: '🇷🇼',
        url: 'https://iptv-org.github.io/iptv/countries/rw.m3u',
        streamCount: 9,
    },
    {
        id: 'iptv-org:country:tz',
        kind: 'country',
        code: 'tz',
        name: 'Tanzania',
        flag: '🇹🇿',
        url: 'https://iptv-org.github.io/iptv/countries/tz.m3u',
        streamCount: 9,
    },
    {
        id: 'iptv-org:country:so',
        kind: 'country',
        code: 'so',
        name: 'Somalia',
        flag: '🇸🇴',
        url: 'https://iptv-org.github.io/iptv/countries/so.m3u',
        streamCount: 8,
    },
    {
        id: 'iptv-org:country:dz',
        kind: 'country',
        code: 'dz',
        name: 'Algeria',
        flag: '🇩🇿',
        url: 'https://iptv-org.github.io/iptv/countries/dz.m3u',
        streamCount: 7,
    },
    {
        id: 'iptv-org:country:is',
        kind: 'country',
        code: 'is',
        name: 'Iceland',
        flag: '🇮🇸',
        url: 'https://iptv-org.github.io/iptv/countries/is.m3u',
        streamCount: 7,
    },
    {
        id: 'iptv-org:country:jm',
        kind: 'country',
        code: 'jm',
        name: 'Jamaica',
        flag: '🇯🇲',
        url: 'https://iptv-org.github.io/iptv/countries/jm.m3u',
        streamCount: 7,
    },
    {
        id: 'iptv-org:country:me',
        kind: 'country',
        code: 'me',
        name: 'Montenegro',
        flag: '🇲🇪',
        url: 'https://iptv-org.github.io/iptv/countries/me.m3u',
        streamCount: 7,
    },
    {
        id: 'iptv-org:country:om',
        kind: 'country',
        code: 'om',
        name: 'Oman',
        flag: '🇴🇲',
        url: 'https://iptv-org.github.io/iptv/countries/om.m3u',
        streamCount: 7,
    },
    {
        id: 'iptv-org:country:tt',
        kind: 'country',
        code: 'tt',
        name: 'Trinidad and Tobago',
        flag: '🇹🇹',
        url: 'https://iptv-org.github.io/iptv/countries/tt.m3u',
        streamCount: 7,
    },
    {
        id: 'iptv-org:country:tn',
        kind: 'country',
        code: 'tn',
        name: 'Tunisia',
        flag: '🇹🇳',
        url: 'https://iptv-org.github.io/iptv/countries/tn.m3u',
        streamCount: 7,
    },
    {
        id: 'iptv-org:country:bq',
        kind: 'country',
        code: 'bq',
        name: 'Bonaire',
        flag: '🇧🇶',
        url: 'https://iptv-org.github.io/iptv/countries/bq.m3u',
        streamCount: 6,
    },
    {
        id: 'iptv-org:country:bf',
        kind: 'country',
        code: 'bf',
        name: 'Burkina Faso',
        flag: '🇧🇫',
        url: 'https://iptv-org.github.io/iptv/countries/bf.m3u',
        streamCount: 6,
    },
    {
        id: 'iptv-org:country:ly',
        kind: 'country',
        code: 'ly',
        name: 'Libya',
        flag: '🇱🇾',
        url: 'https://iptv-org.github.io/iptv/countries/ly.m3u',
        streamCount: 6,
    },
    {
        id: 'iptv-org:country:mq',
        kind: 'country',
        code: 'mq',
        name: 'Martinique',
        flag: '🇲🇶',
        url: 'https://iptv-org.github.io/iptv/countries/mq.m3u',
        streamCount: 6,
    },
    {
        id: 'iptv-org:country:cg',
        kind: 'country',
        code: 'cg',
        name: 'Republic of the Congo',
        flag: '🇨🇬',
        url: 'https://iptv-org.github.io/iptv/countries/cg.m3u',
        streamCount: 6,
    },
    {
        id: 'iptv-org:country:sx',
        kind: 'country',
        code: 'sx',
        name: 'Sint Maarten',
        flag: '🇸🇽',
        url: 'https://iptv-org.github.io/iptv/countries/sx.m3u',
        streamCount: 6,
    },
    {
        id: 'iptv-org:country:bh',
        kind: 'country',
        code: 'bh',
        name: 'Bahrain',
        flag: '🇧🇭',
        url: 'https://iptv-org.github.io/iptv/countries/bh.m3u',
        streamCount: 5,
    },
    {
        id: 'iptv-org:country:gp',
        kind: 'country',
        code: 'gp',
        name: 'Guadeloupe',
        flag: '🇬🇵',
        url: 'https://iptv-org.github.io/iptv/countries/gp.m3u',
        streamCount: 5,
    },
    {
        id: 'iptv-org:country:gn',
        kind: 'country',
        code: 'gn',
        name: 'Guinea',
        flag: '🇬🇳',
        url: 'https://iptv-org.github.io/iptv/countries/gn.m3u',
        streamCount: 5,
    },
    {
        id: 'iptv-org:country:gy',
        kind: 'country',
        code: 'gy',
        name: 'Guyana',
        flag: '🇬🇾',
        url: 'https://iptv-org.github.io/iptv/countries/gy.m3u',
        streamCount: 5,
    },
    {
        id: 'iptv-org:country:ml',
        kind: 'country',
        code: 'ml',
        name: 'Mali',
        flag: '🇲🇱',
        url: 'https://iptv-org.github.io/iptv/countries/ml.m3u',
        streamCount: 5,
    },
    {
        id: 'iptv-org:country:kp',
        kind: 'country',
        code: 'kp',
        name: 'North Korea',
        flag: '🇰🇵',
        url: 'https://iptv-org.github.io/iptv/countries/kp.m3u',
        streamCount: 5,
    },
    {
        id: 'iptv-org:country:bs',
        kind: 'country',
        code: 'bs',
        name: 'Bahamas',
        flag: '🇧🇸',
        url: 'https://iptv-org.github.io/iptv/countries/bs.m3u',
        streamCount: 4,
    },
    {
        id: 'iptv-org:country:cw',
        kind: 'country',
        code: 'cw',
        name: 'Curacao',
        flag: '🇨🇼',
        url: 'https://iptv-org.github.io/iptv/countries/cw.m3u',
        streamCount: 4,
    },
    {
        id: 'iptv-org:country:et',
        kind: 'country',
        code: 'et',
        name: 'Ethiopia',
        flag: '🇪🇹',
        url: 'https://iptv-org.github.io/iptv/countries/et.m3u',
        streamCount: 4,
    },
    {
        id: 'iptv-org:country:ne',
        kind: 'country',
        code: 'ne',
        name: 'Niger',
        flag: '🇳🇪',
        url: 'https://iptv-org.github.io/iptv/countries/ne.m3u',
        streamCount: 4,
    },
    {
        id: 'iptv-org:country:ye',
        kind: 'country',
        code: 'ye',
        name: 'Yemen',
        flag: '🇾🇪',
        url: 'https://iptv-org.github.io/iptv/countries/ye.m3u',
        streamCount: 4,
    },
    {
        id: 'iptv-org:country:ao',
        kind: 'country',
        code: 'ao',
        name: 'Angola',
        flag: '🇦🇴',
        url: 'https://iptv-org.github.io/iptv/countries/ao.m3u',
        streamCount: 3,
    },
    {
        id: 'iptv-org:country:mc',
        kind: 'country',
        code: 'mc',
        name: 'Monaco',
        flag: '🇲🇨',
        url: 'https://iptv-org.github.io/iptv/countries/mc.m3u',
        streamCount: 3,
    },
    {
        id: 'iptv-org:country:lc',
        kind: 'country',
        code: 'lc',
        name: 'Saint Lucia',
        flag: '🇱🇨',
        url: 'https://iptv-org.github.io/iptv/countries/lc.m3u',
        streamCount: 3,
    },
    {
        id: 'iptv-org:country:sd',
        kind: 'country',
        code: 'sd',
        name: 'Sudan',
        flag: '🇸🇩',
        url: 'https://iptv-org.github.io/iptv/countries/sd.m3u',
        streamCount: 3,
    },
    {
        id: 'iptv-org:country:eh',
        kind: 'country',
        code: 'eh',
        name: 'Western Sahara',
        flag: '🇪🇭',
        url: 'https://iptv-org.github.io/iptv/countries/eh.m3u',
        streamCount: 3,
    },
    {
        id: 'iptv-org:region:emea',
        kind: 'region',
        code: 'emea',
        name: 'Europe, the Middle East and Africa',
        url: 'https://iptv-org.github.io/iptv/regions/emea.m3u',
        streamCount: 144,
    },
    {
        id: 'iptv-org:region:hispam',
        kind: 'region',
        code: 'hispam',
        name: 'Hispanic America',
        url: 'https://iptv-org.github.io/iptv/regions/hispam.m3u',
        streamCount: 143,
    },
    {
        id: 'iptv-org:region:latam',
        kind: 'region',
        code: 'latam',
        name: 'Latin America',
        url: 'https://iptv-org.github.io/iptv/regions/latam.m3u',
        streamCount: 142,
    },
    {
        id: 'iptv-org:region:apac',
        kind: 'region',
        code: 'apac',
        name: 'Asia-Pacific',
        url: 'https://iptv-org.github.io/iptv/regions/apac.m3u',
        streamCount: 141,
    },
    {
        id: 'iptv-org:region:amer',
        kind: 'region',
        code: 'amer',
        name: 'Americas',
        url: 'https://iptv-org.github.io/iptv/regions/amer.m3u',
        streamCount: 133,
    },
    {
        id: 'iptv-org:region:eur',
        kind: 'region',
        code: 'eur',
        name: 'Europe',
        url: 'https://iptv-org.github.io/iptv/regions/eur.m3u',
        streamCount: 128,
    },
    {
        id: 'iptv-org:region:arab',
        kind: 'region',
        code: 'arab',
        name: 'Arab world',
        url: 'https://iptv-org.github.io/iptv/regions/arab.m3u',
        streamCount: 86,
    },
    {
        id: 'iptv-org:region:carib',
        kind: 'region',
        code: 'carib',
        name: 'Caribbean',
        url: 'https://iptv-org.github.io/iptv/regions/carib.m3u',
        streamCount: 76,
    },
    {
        id: 'iptv-org:region:afr',
        kind: 'region',
        code: 'afr',
        name: 'Africa',
        url: 'https://iptv-org.github.io/iptv/regions/afr.m3u',
        streamCount: 66,
    },
    {
        id: 'iptv-org:region:cenamer',
        kind: 'region',
        code: 'cenamer',
        name: 'Central America',
        url: 'https://iptv-org.github.io/iptv/regions/cenamer.m3u',
        streamCount: 60,
    },
    {
        id: 'iptv-org:region:asia',
        kind: 'region',
        code: 'asia',
        name: 'Asia',
        url: 'https://iptv-org.github.io/iptv/regions/asia.m3u',
        streamCount: 59,
    },
    {
        id: 'iptv-org:region:maghreb',
        kind: 'region',
        code: 'maghreb',
        name: 'Maghreb',
        url: 'https://iptv-org.github.io/iptv/regions/maghreb.m3u',
        streamCount: 45,
    },
    {
        id: 'iptv-org:region:sea',
        kind: 'region',
        code: 'sea',
        name: 'Southeast Asia',
        url: 'https://iptv-org.github.io/iptv/regions/sea.m3u',
        streamCount: 39,
    },
    {
        id: 'iptv-org:region:eu',
        kind: 'region',
        code: 'eu',
        name: 'European Union',
        url: 'https://iptv-org.github.io/iptv/regions/eu.m3u',
        streamCount: 36,
    },
    {
        id: 'iptv-org:region:oce',
        kind: 'region',
        code: 'oce',
        name: 'Oceania',
        url: 'https://iptv-org.github.io/iptv/regions/oce.m3u',
        streamCount: 34,
    },
    {
        id: 'iptv-org:region:ww',
        kind: 'region',
        code: 'ww',
        name: 'Worldwide',
        url: 'https://iptv-org.github.io/iptv/regions/ww.m3u',
        streamCount: 34,
    },
    {
        id: 'iptv-org:region:noram',
        kind: 'region',
        code: 'noram',
        name: 'North America',
        url: 'https://iptv-org.github.io/iptv/regions/noram.m3u',
        streamCount: 28,
    },
    {
        id: 'iptv-org:region:cis',
        kind: 'region',
        code: 'cis',
        name: 'Commonwealth of Independent States',
        url: 'https://iptv-org.github.io/iptv/regions/cis.m3u',
        streamCount: 20,
    },
    {
        id: 'iptv-org:region:mena',
        kind: 'region',
        code: 'mena',
        name: 'Middle East and North Africa',
        url: 'https://iptv-org.github.io/iptv/regions/mena.m3u',
        streamCount: 20,
    },
    {
        id: 'iptv-org:region:sas',
        kind: 'region',
        code: 'sas',
        name: 'South Asia',
        url: 'https://iptv-org.github.io/iptv/regions/sas.m3u',
        streamCount: 15,
    },
    {
        id: 'iptv-org:region:ssa',
        kind: 'region',
        code: 'ssa',
        name: 'Sub-Saharan Africa',
        url: 'https://iptv-org.github.io/iptv/regions/ssa.m3u',
        streamCount: 14,
    },
    {
        id: 'iptv-org:region:mideast',
        kind: 'region',
        code: 'mideast',
        name: 'Middle East',
        url: 'https://iptv-org.github.io/iptv/regions/mideast.m3u',
        streamCount: 10,
    },
    {
        id: 'iptv-org:region:southam',
        kind: 'region',
        code: 'southam',
        name: 'South America',
        url: 'https://iptv-org.github.io/iptv/regions/southam.m3u',
        streamCount: 9,
    },
    {
        id: 'iptv-org:region:cas',
        kind: 'region',
        code: 'cas',
        name: 'Central Asia',
        url: 'https://iptv-org.github.io/iptv/regions/cas.m3u',
        streamCount: 7,
    },
    {
        id: 'iptv-org:region:balkan',
        kind: 'region',
        code: 'balkan',
        name: 'Balkan',
        url: 'https://iptv-org.github.io/iptv/regions/balkan.m3u',
        streamCount: 4,
    },
    {
        id: 'iptv-org:region:nord',
        kind: 'region',
        code: 'nord',
        name: 'Nordics',
        url: 'https://iptv-org.github.io/iptv/regions/nord.m3u',
        streamCount: 4,
    },
    {
        id: 'iptv-org:region:lac',
        kind: 'region',
        code: 'lac',
        name: 'Latin America and the Caribbean',
        url: 'https://iptv-org.github.io/iptv/regions/lac.m3u',
        streamCount: 3,
    },
    {
        id: 'iptv-org:category:general',
        kind: 'category',
        code: 'general',
        name: 'General',
        url: 'https://iptv-org.github.io/iptv/categories/general.m3u',
        streamCount: 3455,
    },
    {
        id: 'iptv-org:category:news',
        kind: 'category',
        code: 'news',
        name: 'News',
        url: 'https://iptv-org.github.io/iptv/categories/news.m3u',
        streamCount: 1704,
    },
    {
        id: 'iptv-org:category:entertainment',
        kind: 'category',
        code: 'entertainment',
        name: 'Entertainment',
        url: 'https://iptv-org.github.io/iptv/categories/entertainment.m3u',
        streamCount: 1162,
    },
    {
        id: 'iptv-org:category:music',
        kind: 'category',
        code: 'music',
        name: 'Music',
        url: 'https://iptv-org.github.io/iptv/categories/music.m3u',
        streamCount: 964,
    },
    {
        id: 'iptv-org:category:religious',
        kind: 'category',
        code: 'religious',
        name: 'Religious',
        url: 'https://iptv-org.github.io/iptv/categories/religious.m3u',
        streamCount: 936,
    },
    {
        id: 'iptv-org:category:movies',
        kind: 'category',
        code: 'movies',
        name: 'Movies',
        url: 'https://iptv-org.github.io/iptv/categories/movies.m3u',
        streamCount: 920,
    },
    {
        id: 'iptv-org:category:series',
        kind: 'category',
        code: 'series',
        name: 'Series',
        url: 'https://iptv-org.github.io/iptv/categories/series.m3u',
        streamCount: 770,
    },
    {
        id: 'iptv-org:category:sports',
        kind: 'category',
        code: 'sports',
        name: 'Sports',
        url: 'https://iptv-org.github.io/iptv/categories/sports.m3u',
        streamCount: 708,
    },
    {
        id: 'iptv-org:category:kids',
        kind: 'category',
        code: 'kids',
        name: 'Kids',
        url: 'https://iptv-org.github.io/iptv/categories/kids.m3u',
        streamCount: 537,
    },
    {
        id: 'iptv-org:category:documentary',
        kind: 'category',
        code: 'documentary',
        name: 'Documentary',
        url: 'https://iptv-org.github.io/iptv/categories/documentary.m3u',
        streamCount: 375,
    },
    {
        id: 'iptv-org:category:education',
        kind: 'category',
        code: 'education',
        name: 'Education',
        url: 'https://iptv-org.github.io/iptv/categories/education.m3u',
        streamCount: 284,
    },
    {
        id: 'iptv-org:category:comedy',
        kind: 'category',
        code: 'comedy',
        name: 'Comedy',
        url: 'https://iptv-org.github.io/iptv/categories/comedy.m3u',
        streamCount: 273,
    },
    {
        id: 'iptv-org:category:culture',
        kind: 'category',
        code: 'culture',
        name: 'Culture',
        url: 'https://iptv-org.github.io/iptv/categories/culture.m3u',
        streamCount: 243,
    },
    {
        id: 'iptv-org:category:animation',
        kind: 'category',
        code: 'animation',
        name: 'Animation',
        url: 'https://iptv-org.github.io/iptv/categories/animation.m3u',
        streamCount: 217,
    },
    {
        id: 'iptv-org:category:legislative',
        kind: 'category',
        code: 'legislative',
        name: 'Legislative',
        url: 'https://iptv-org.github.io/iptv/categories/legislative.m3u',
        streamCount: 212,
    },
    {
        id: 'iptv-org:category:lifestyle',
        kind: 'category',
        code: 'lifestyle',
        name: 'Lifestyle',
        url: 'https://iptv-org.github.io/iptv/categories/lifestyle.m3u',
        streamCount: 175,
    },
    {
        id: 'iptv-org:category:outdoor',
        kind: 'category',
        code: 'outdoor',
        name: 'Outdoor',
        url: 'https://iptv-org.github.io/iptv/categories/outdoor.m3u',
        streamCount: 139,
    },
    {
        id: 'iptv-org:category:business',
        kind: 'category',
        code: 'business',
        name: 'Business',
        url: 'https://iptv-org.github.io/iptv/categories/business.m3u',
        streamCount: 119,
    },
    {
        id: 'iptv-org:category:classic',
        kind: 'category',
        code: 'classic',
        name: 'Classic',
        url: 'https://iptv-org.github.io/iptv/categories/classic.m3u',
        streamCount: 117,
    },
    {
        id: 'iptv-org:category:travel',
        kind: 'category',
        code: 'travel',
        name: 'Travel',
        url: 'https://iptv-org.github.io/iptv/categories/travel.m3u',
        streamCount: 95,
    },
    {
        id: 'iptv-org:category:shop',
        kind: 'category',
        code: 'shop',
        name: 'Shop',
        url: 'https://iptv-org.github.io/iptv/categories/shop.m3u',
        streamCount: 94,
    },
    {
        id: 'iptv-org:category:family',
        kind: 'category',
        code: 'family',
        name: 'Family',
        url: 'https://iptv-org.github.io/iptv/categories/family.m3u',
        streamCount: 86,
    },
    {
        id: 'iptv-org:category:cooking',
        kind: 'category',
        code: 'cooking',
        name: 'Cooking',
        url: 'https://iptv-org.github.io/iptv/categories/cooking.m3u',
        streamCount: 73,
    },
    {
        id: 'iptv-org:category:public',
        kind: 'category',
        code: 'public',
        name: 'Public',
        url: 'https://iptv-org.github.io/iptv/categories/public.m3u',
        streamCount: 57,
    },
    {
        id: 'iptv-org:category:auto',
        kind: 'category',
        code: 'auto',
        name: 'Auto',
        url: 'https://iptv-org.github.io/iptv/categories/auto.m3u',
        streamCount: 53,
    },
    {
        id: 'iptv-org:category:science',
        kind: 'category',
        code: 'science',
        name: 'Science',
        url: 'https://iptv-org.github.io/iptv/categories/science.m3u',
        streamCount: 33,
    },
    {
        id: 'iptv-org:category:weather',
        kind: 'category',
        code: 'weather',
        name: 'Weather',
        url: 'https://iptv-org.github.io/iptv/categories/weather.m3u',
        streamCount: 27,
    },
    {
        id: 'iptv-org:category:relax',
        kind: 'category',
        code: 'relax',
        name: 'Relax',
        url: 'https://iptv-org.github.io/iptv/categories/relax.m3u',
        streamCount: 24,
    },
    {
        id: 'iptv-org:language:eng',
        kind: 'language',
        code: 'eng',
        name: 'English',
        url: 'https://iptv-org.github.io/iptv/languages/eng.m3u',
        streamCount: 4410,
    },
    {
        id: 'iptv-org:language:spa',
        kind: 'language',
        code: 'spa',
        name: 'Spanish',
        url: 'https://iptv-org.github.io/iptv/languages/spa.m3u',
        streamCount: 2839,
    },
    {
        id: 'iptv-org:language:rus',
        kind: 'language',
        code: 'rus',
        name: 'Russian',
        url: 'https://iptv-org.github.io/iptv/languages/rus.m3u',
        streamCount: 1131,
    },
    {
        id: 'iptv-org:language:por',
        kind: 'language',
        code: 'por',
        name: 'Portuguese',
        url: 'https://iptv-org.github.io/iptv/languages/por.m3u',
        streamCount: 768,
    },
    {
        id: 'iptv-org:language:fra',
        kind: 'language',
        code: 'fra',
        name: 'French',
        url: 'https://iptv-org.github.io/iptv/languages/fra.m3u',
        streamCount: 576,
    },
    {
        id: 'iptv-org:language:hin',
        kind: 'language',
        code: 'hin',
        name: 'Hindi',
        url: 'https://iptv-org.github.io/iptv/languages/hin.m3u',
        streamCount: 548,
    },
    {
        id: 'iptv-org:language:ara',
        kind: 'language',
        code: 'ara',
        name: 'Arabic',
        url: 'https://iptv-org.github.io/iptv/languages/ara.m3u',
        streamCount: 467,
    },
    {
        id: 'iptv-org:language:deu',
        kind: 'language',
        code: 'deu',
        name: 'German',
        url: 'https://iptv-org.github.io/iptv/languages/deu.m3u',
        streamCount: 399,
    },
    {
        id: 'iptv-org:language:ita',
        kind: 'language',
        code: 'ita',
        name: 'Italian',
        url: 'https://iptv-org.github.io/iptv/languages/ita.m3u',
        streamCount: 368,
    },
    {
        id: 'iptv-org:language:zho',
        kind: 'language',
        code: 'zho',
        name: 'Chinese',
        url: 'https://iptv-org.github.io/iptv/languages/zho.m3u',
        streamCount: 365,
    },
    {
        id: 'iptv-org:language:fas',
        kind: 'language',
        code: 'fas',
        name: 'Persian',
        url: 'https://iptv-org.github.io/iptv/languages/fas.m3u',
        streamCount: 234,
    },
    {
        id: 'iptv-org:language:nld',
        kind: 'language',
        code: 'nld',
        name: 'Dutch',
        url: 'https://iptv-org.github.io/iptv/languages/nld.m3u',
        streamCount: 226,
    },
    {
        id: 'iptv-org:language:tur',
        kind: 'language',
        code: 'tur',
        name: 'Turkish',
        url: 'https://iptv-org.github.io/iptv/languages/tur.m3u',
        streamCount: 222,
    },
    {
        id: 'iptv-org:language:ind',
        kind: 'language',
        code: 'ind',
        name: 'Indonesian',
        url: 'https://iptv-org.github.io/iptv/languages/ind.m3u',
        streamCount: 200,
    },
    {
        id: 'iptv-org:language:hun',
        kind: 'language',
        code: 'hun',
        name: 'Hungarian',
        url: 'https://iptv-org.github.io/iptv/languages/hun.m3u',
        streamCount: 165,
    },
    {
        id: 'iptv-org:language:tam',
        kind: 'language',
        code: 'tam',
        name: 'Tamil',
        url: 'https://iptv-org.github.io/iptv/languages/tam.m3u',
        streamCount: 164,
    },
    {
        id: 'iptv-org:language:ukr',
        kind: 'language',
        code: 'ukr',
        name: 'Ukrainian',
        url: 'https://iptv-org.github.io/iptv/languages/ukr.m3u',
        streamCount: 162,
    },
    {
        id: 'iptv-org:language:dan',
        kind: 'language',
        code: 'dan',
        name: 'Danish',
        url: 'https://iptv-org.github.io/iptv/languages/dan.m3u',
        streamCount: 158,
    },
    {
        id: 'iptv-org:language:vie',
        kind: 'language',
        code: 'vie',
        name: 'Vietnamese',
        url: 'https://iptv-org.github.io/iptv/languages/vie.m3u',
        streamCount: 158,
    },
    {
        id: 'iptv-org:language:ron',
        kind: 'language',
        code: 'ron',
        name: 'Romanian',
        url: 'https://iptv-org.github.io/iptv/languages/ron.m3u',
        streamCount: 142,
    },
    {
        id: 'iptv-org:language:swe',
        kind: 'language',
        code: 'swe',
        name: 'Swedish',
        url: 'https://iptv-org.github.io/iptv/languages/swe.m3u',
        streamCount: 140,
    },
    {
        id: 'iptv-org:language:nor',
        kind: 'language',
        code: 'nor',
        name: 'Norwegian',
        url: 'https://iptv-org.github.io/iptv/languages/nor.m3u',
        streamCount: 127,
    },
    {
        id: 'iptv-org:language:pol',
        kind: 'language',
        code: 'pol',
        name: 'Polish',
        url: 'https://iptv-org.github.io/iptv/languages/pol.m3u',
        streamCount: 115,
    },
    {
        id: 'iptv-org:language:ben',
        kind: 'language',
        code: 'ben',
        name: 'Bengali',
        url: 'https://iptv-org.github.io/iptv/languages/ben.m3u',
        streamCount: 112,
    },
    {
        id: 'iptv-org:language:tel',
        kind: 'language',
        code: 'tel',
        name: 'Telugu',
        url: 'https://iptv-org.github.io/iptv/languages/tel.m3u',
        streamCount: 106,
    },
    {
        id: 'iptv-org:language:mal',
        kind: 'language',
        code: 'mal',
        name: 'Malayalam',
        url: 'https://iptv-org.github.io/iptv/languages/mal.m3u',
        streamCount: 105,
    },
    {
        id: 'iptv-org:language:srp',
        kind: 'language',
        code: 'srp',
        name: 'Serbian',
        url: 'https://iptv-org.github.io/iptv/languages/srp.m3u',
        streamCount: 102,
    },
    {
        id: 'iptv-org:language:tha',
        kind: 'language',
        code: 'tha',
        name: 'Thai',
        url: 'https://iptv-org.github.io/iptv/languages/tha.m3u',
        streamCount: 95,
    },
    {
        id: 'iptv-org:language:urd',
        kind: 'language',
        code: 'urd',
        name: 'Urdu',
        url: 'https://iptv-org.github.io/iptv/languages/urd.m3u',
        streamCount: 95,
    },
    {
        id: 'iptv-org:language:ell',
        kind: 'language',
        code: 'ell',
        name: 'Greek',
        url: 'https://iptv-org.github.io/iptv/languages/ell.m3u',
        streamCount: 93,
    },
    {
        id: 'iptv-org:language:kor',
        kind: 'language',
        code: 'kor',
        name: 'Korean',
        url: 'https://iptv-org.github.io/iptv/languages/kor.m3u',
        streamCount: 91,
    },
    {
        id: 'iptv-org:language:bul',
        kind: 'language',
        code: 'bul',
        name: 'Bulgarian',
        url: 'https://iptv-org.github.io/iptv/languages/bul.m3u',
        streamCount: 89,
    },
    {
        id: 'iptv-org:language:mon',
        kind: 'language',
        code: 'mon',
        name: 'Mongolian',
        url: 'https://iptv-org.github.io/iptv/languages/mon.m3u',
        streamCount: 84,
    },
    {
        id: 'iptv-org:language:ces',
        kind: 'language',
        code: 'ces',
        name: 'Czech',
        url: 'https://iptv-org.github.io/iptv/languages/ces.m3u',
        streamCount: 79,
    },
    {
        id: 'iptv-org:language:pan',
        kind: 'language',
        code: 'pan',
        name: 'Panjabi',
        url: 'https://iptv-org.github.io/iptv/languages/pan.m3u',
        streamCount: 74,
    },
    {
        id: 'iptv-org:language:sqi',
        kind: 'language',
        code: 'sqi',
        name: 'Albanian',
        url: 'https://iptv-org.github.io/iptv/languages/sqi.m3u',
        streamCount: 67,
    },
    {
        id: 'iptv-org:language:cat',
        kind: 'language',
        code: 'cat',
        name: 'Catalan',
        url: 'https://iptv-org.github.io/iptv/languages/cat.m3u',
        streamCount: 67,
    },
    {
        id: 'iptv-org:language:slk',
        kind: 'language',
        code: 'slk',
        name: 'Slovak',
        url: 'https://iptv-org.github.io/iptv/languages/slk.m3u',
        streamCount: 63,
    },
    {
        id: 'iptv-org:language:kan',
        kind: 'language',
        code: 'kan',
        name: 'Kannada',
        url: 'https://iptv-org.github.io/iptv/languages/kan.m3u',
        streamCount: 56,
    },
    {
        id: 'iptv-org:language:kaz',
        kind: 'language',
        code: 'kaz',
        name: 'Kazakh',
        url: 'https://iptv-org.github.io/iptv/languages/kaz.m3u',
        streamCount: 48,
    },
    {
        id: 'iptv-org:language:mar',
        kind: 'language',
        code: 'mar',
        name: 'Marathi',
        url: 'https://iptv-org.github.io/iptv/languages/mar.m3u',
        streamCount: 43,
    },
    {
        id: 'iptv-org:language:kur',
        kind: 'language',
        code: 'kur',
        name: 'Kurdish',
        url: 'https://iptv-org.github.io/iptv/languages/kur.m3u',
        streamCount: 40,
    },
    {
        id: 'iptv-org:language:uzb',
        kind: 'language',
        code: 'uzb',
        name: 'Uzbek',
        url: 'https://iptv-org.github.io/iptv/languages/uzb.m3u',
        streamCount: 37,
    },
    {
        id: 'iptv-org:language:fin',
        kind: 'language',
        code: 'fin',
        name: 'Finnish',
        url: 'https://iptv-org.github.io/iptv/languages/fin.m3u',
        streamCount: 36,
    },
    {
        id: 'iptv-org:language:khm',
        kind: 'language',
        code: 'khm',
        name: 'Khmer',
        url: 'https://iptv-org.github.io/iptv/languages/khm.m3u',
        streamCount: 35,
    },
    {
        id: 'iptv-org:language:hrv',
        kind: 'language',
        code: 'hrv',
        name: 'Croatian',
        url: 'https://iptv-org.github.io/iptv/languages/hrv.m3u',
        streamCount: 30,
    },
    {
        id: 'iptv-org:language:heb',
        kind: 'language',
        code: 'heb',
        name: 'Hebrew',
        url: 'https://iptv-org.github.io/iptv/languages/heb.m3u',
        streamCount: 30,
    },
    {
        id: 'iptv-org:language:mkd',
        kind: 'language',
        code: 'mkd',
        name: 'Macedonian',
        url: 'https://iptv-org.github.io/iptv/languages/mkd.m3u',
        streamCount: 30,
    },
    {
        id: 'iptv-org:language:asm',
        kind: 'language',
        code: 'asm',
        name: 'Assamese',
        url: 'https://iptv-org.github.io/iptv/languages/asm.m3u',
        streamCount: 27,
    },
    {
        id: 'iptv-org:language:jpn',
        kind: 'language',
        code: 'jpn',
        name: 'Japanese',
        url: 'https://iptv-org.github.io/iptv/languages/jpn.m3u',
        streamCount: 27,
    },
    {
        id: 'iptv-org:language:bho',
        kind: 'language',
        code: 'bho',
        name: 'Bhojpuri',
        url: 'https://iptv-org.github.io/iptv/languages/bho.m3u',
        streamCount: 26,
    },
    {
        id: 'iptv-org:language:aze',
        kind: 'language',
        code: 'aze',
        name: 'Azerbaijani',
        url: 'https://iptv-org.github.io/iptv/languages/aze.m3u',
        streamCount: 25,
    },
    {
        id: 'iptv-org:language:slv',
        kind: 'language',
        code: 'slv',
        name: 'Slovenian',
        url: 'https://iptv-org.github.io/iptv/languages/slv.m3u',
        streamCount: 25,
    },
    {
        id: 'iptv-org:language:kat',
        kind: 'language',
        code: 'kat',
        name: 'Georgian',
        url: 'https://iptv-org.github.io/iptv/languages/kat.m3u',
        streamCount: 24,
    },
    {
        id: 'iptv-org:language:pap',
        kind: 'language',
        code: 'pap',
        name: 'Papiamento',
        url: 'https://iptv-org.github.io/iptv/languages/pap.m3u',
        streamCount: 24,
    },
    {
        id: 'iptv-org:language:pus',
        kind: 'language',
        code: 'pus',
        name: 'Pashto',
        url: 'https://iptv-org.github.io/iptv/languages/pus.m3u',
        streamCount: 24,
    },
    {
        id: 'iptv-org:language:swa',
        kind: 'language',
        code: 'swa',
        name: 'Swahili',
        url: 'https://iptv-org.github.io/iptv/languages/swa.m3u',
        streamCount: 23,
    },
    {
        id: 'iptv-org:language:lit',
        kind: 'language',
        code: 'lit',
        name: 'Lithuanian',
        url: 'https://iptv-org.github.io/iptv/languages/lit.m3u',
        streamCount: 21,
    },
    {
        id: 'iptv-org:language:mya',
        kind: 'language',
        code: 'mya',
        name: 'Burmese',
        url: 'https://iptv-org.github.io/iptv/languages/mya.m3u',
        streamCount: 19,
    },
    {
        id: 'iptv-org:language:lav',
        kind: 'language',
        code: 'lav',
        name: 'Latvian',
        url: 'https://iptv-org.github.io/iptv/languages/lav.m3u',
        streamCount: 18,
    },
    {
        id: 'iptv-org:language:nep',
        kind: 'language',
        code: 'nep',
        name: 'Nepali',
        url: 'https://iptv-org.github.io/iptv/languages/nep.m3u',
        streamCount: 18,
    },
    {
        id: 'iptv-org:language:tuk',
        kind: 'language',
        code: 'tuk',
        name: 'Turkmen',
        url: 'https://iptv-org.github.io/iptv/languages/tuk.m3u',
        streamCount: 18,
    },
    {
        id: 'iptv-org:language:bel',
        kind: 'language',
        code: 'bel',
        name: 'Belarusian',
        url: 'https://iptv-org.github.io/iptv/languages/bel.m3u',
        streamCount: 17,
    },
    {
        id: 'iptv-org:language:msa',
        kind: 'language',
        code: 'msa',
        name: 'Malay',
        url: 'https://iptv-org.github.io/iptv/languages/msa.m3u',
        streamCount: 17,
    },
    {
        id: 'iptv-org:language:bos',
        kind: 'language',
        code: 'bos',
        name: 'Bosnian',
        url: 'https://iptv-org.github.io/iptv/languages/bos.m3u',
        streamCount: 15,
    },
    {
        id: 'iptv-org:language:prd',
        kind: 'language',
        code: 'prd',
        name: 'Dari (Parsi)',
        url: 'https://iptv-org.github.io/iptv/languages/prd.m3u',
        streamCount: 15,
    },
    {
        id: 'iptv-org:language:guj',
        kind: 'language',
        code: 'guj',
        name: 'Gujarati',
        url: 'https://iptv-org.github.io/iptv/languages/guj.m3u',
        streamCount: 15,
    },
    {
        id: 'iptv-org:language:hat',
        kind: 'language',
        code: 'hat',
        name: 'Haitian',
        url: 'https://iptv-org.github.io/iptv/languages/hat.m3u',
        streamCount: 15,
    },
    {
        id: 'iptv-org:language:tgk',
        kind: 'language',
        code: 'tgk',
        name: 'Tajik',
        url: 'https://iptv-org.github.io/iptv/languages/tgk.m3u',
        streamCount: 15,
    },
    {
        id: 'iptv-org:language:hye',
        kind: 'language',
        code: 'hye',
        name: 'Armenian',
        url: 'https://iptv-org.github.io/iptv/languages/hye.m3u',
        streamCount: 14,
    },
    {
        id: 'iptv-org:language:mlt',
        kind: 'language',
        code: 'mlt',
        name: 'Maltese',
        url: 'https://iptv-org.github.io/iptv/languages/mlt.m3u',
        streamCount: 14,
    },
    {
        id: 'iptv-org:language:kir',
        kind: 'language',
        code: 'kir',
        name: 'Kirghiz',
        url: 'https://iptv-org.github.io/iptv/languages/kir.m3u',
        streamCount: 13,
    },
    {
        id: 'iptv-org:language:ori',
        kind: 'language',
        code: 'ori',
        name: 'Oriya (macrolanguage)',
        url: 'https://iptv-org.github.io/iptv/languages/ori.m3u',
        streamCount: 13,
    },
    {
        id: 'iptv-org:language:tgl',
        kind: 'language',
        code: 'tgl',
        name: 'Tagalog',
        url: 'https://iptv-org.github.io/iptv/languages/tgl.m3u',
        streamCount: 12,
    },
    {
        id: 'iptv-org:language:som',
        kind: 'language',
        code: 'som',
        name: 'Somali',
        url: 'https://iptv-org.github.io/iptv/languages/som.m3u',
        streamCount: 11,
    },
    {
        id: 'iptv-org:language:eus',
        kind: 'language',
        code: 'eus',
        name: 'Basque',
        url: 'https://iptv-org.github.io/iptv/languages/eus.m3u',
        streamCount: 10,
    },
    {
        id: 'iptv-org:language:est',
        kind: 'language',
        code: 'est',
        name: 'Estonian',
        url: 'https://iptv-org.github.io/iptv/languages/est.m3u',
        streamCount: 10,
    },
    {
        id: 'iptv-org:language:lug',
        kind: 'language',
        code: 'lug',
        name: 'Ganda',
        url: 'https://iptv-org.github.io/iptv/languages/lug.m3u',
        streamCount: 9,
    },
    {
        id: 'iptv-org:language:kin',
        kind: 'language',
        code: 'kin',
        name: 'Kinyarwanda',
        url: 'https://iptv-org.github.io/iptv/languages/kin.m3u',
        streamCount: 9,
    },
    {
        id: 'iptv-org:language:mai',
        kind: 'language',
        code: 'mai',
        name: 'Maithili',
        url: 'https://iptv-org.github.io/iptv/languages/mai.m3u',
        streamCount: 9,
    },
    {
        id: 'iptv-org:language:div',
        kind: 'language',
        code: 'div',
        name: 'Dhivehi',
        url: 'https://iptv-org.github.io/iptv/languages/div.m3u',
        streamCount: 8,
    },
    {
        id: 'iptv-org:language:ltz',
        kind: 'language',
        code: 'ltz',
        name: 'Letzeburgesch',
        url: 'https://iptv-org.github.io/iptv/languages/ltz.m3u',
        streamCount: 8,
    },
    {
        id: 'iptv-org:language:sin',
        kind: 'language',
        code: 'sin',
        name: 'Sinhala',
        url: 'https://iptv-org.github.io/iptv/languages/sin.m3u',
        streamCount: 8,
    },
    {
        id: 'iptv-org:language:yue',
        kind: 'language',
        code: 'yue',
        name: 'Yue Chinese',
        url: 'https://iptv-org.github.io/iptv/languages/yue.m3u',
        streamCount: 8,
    },
    {
        id: 'iptv-org:language:amh',
        kind: 'language',
        code: 'amh',
        name: 'Amharic',
        url: 'https://iptv-org.github.io/iptv/languages/amh.m3u',
        streamCount: 7,
    },
    {
        id: 'iptv-org:language:isl',
        kind: 'language',
        code: 'isl',
        name: 'Icelandic',
        url: 'https://iptv-org.github.io/iptv/languages/isl.m3u',
        streamCount: 7,
    },
    {
        id: 'iptv-org:language:afr',
        kind: 'language',
        code: 'afr',
        name: 'Afrikaans',
        url: 'https://iptv-org.github.io/iptv/languages/afr.m3u',
        streamCount: 6,
    },
    {
        id: 'iptv-org:language:jav',
        kind: 'language',
        code: 'jav',
        name: 'Javanese',
        url: 'https://iptv-org.github.io/iptv/languages/jav.m3u',
        streamCount: 6,
    },
    {
        id: 'iptv-org:language:aym',
        kind: 'language',
        code: 'aym',
        name: 'Aymara',
        url: 'https://iptv-org.github.io/iptv/languages/aym.m3u',
        streamCount: 5,
    },
    {
        id: 'iptv-org:language:lao',
        kind: 'language',
        code: 'lao',
        name: 'Lao',
        url: 'https://iptv-org.github.io/iptv/languages/lao.m3u',
        streamCount: 5,
    },
    {
        id: 'iptv-org:language:que',
        kind: 'language',
        code: 'que',
        name: 'Quechua',
        url: 'https://iptv-org.github.io/iptv/languages/que.m3u',
        streamCount: 5,
    },
    {
        id: 'iptv-org:language:cym',
        kind: 'language',
        code: 'cym',
        name: 'Welsh',
        url: 'https://iptv-org.github.io/iptv/languages/cym.m3u',
        streamCount: 5,
    },
    {
        id: 'iptv-org:language:wol',
        kind: 'language',
        code: 'wol',
        name: 'Wolof',
        url: 'https://iptv-org.github.io/iptv/languages/wol.m3u',
        streamCount: 5,
    },
    {
        id: 'iptv-org:language:zza',
        kind: 'language',
        code: 'zza',
        name: 'Dimili',
        url: 'https://iptv-org.github.io/iptv/languages/zza.m3u',
        streamCount: 4,
    },
    {
        id: 'iptv-org:language:gla',
        kind: 'language',
        code: 'gla',
        name: 'Gaelic',
        url: 'https://iptv-org.github.io/iptv/languages/gla.m3u',
        streamCount: 4,
    },
    {
        id: 'iptv-org:language:gle',
        kind: 'language',
        code: 'gle',
        name: 'Irish',
        url: 'https://iptv-org.github.io/iptv/languages/gle.m3u',
        streamCount: 4,
    },
    {
        id: 'iptv-org:language:lin',
        kind: 'language',
        code: 'lin',
        name: 'Lingala',
        url: 'https://iptv-org.github.io/iptv/languages/lin.m3u',
        streamCount: 4,
    },
    {
        id: 'iptv-org:language:cmn',
        kind: 'language',
        code: 'cmn',
        name: 'Mandarin Chinese',
        url: 'https://iptv-org.github.io/iptv/languages/cmn.m3u',
        streamCount: 4,
    },
    {
        id: 'iptv-org:language:sun',
        kind: 'language',
        code: 'sun',
        name: 'Sundanese',
        url: 'https://iptv-org.github.io/iptv/languages/sun.m3u',
        streamCount: 4,
    },
    {
        id: 'iptv-org:language:kik',
        kind: 'language',
        code: 'kik',
        name: 'Gikuyu',
        url: 'https://iptv-org.github.io/iptv/languages/kik.m3u',
        streamCount: 3,
    },
    {
        id: 'iptv-org:language:uig',
        kind: 'language',
        code: 'uig',
        name: 'Uighur',
        url: 'https://iptv-org.github.io/iptv/languages/uig.m3u',
        streamCount: 3,
    },
];
